name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install --no-install-recommends -y gcc make libssl-dev libcurl4-openssl-dev libmagic-dev
      - name: Build
        run: |
          make
          make clean
          make WITH_LIBMAGIC=1
          make clean
          make WITH_LIBMAGIC=0
